name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker image
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        run: |
          docker build -t $DOCKER_HUB_USERNAME/ms-fazri-betest:latest .
          docker push $DOCKER_HUB_USERNAME/ms-fazri-betest:latest

      - name: Deploy to VM
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST_SSH_USERNAME: ${{ secrets.HOST_SSH_USERNAME }}
          HOST_SSH_PASSWORD: ${{ secrets.HOST_SSH_PASSWORD }}
          HOST_SSH_PORT: ${{ secrets.HOST_SSH_PORT }}
          HOST_IP: ${{ secrets.HOST_IP }}
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem $HOST_SSH_USERNAME@$HOST_IP << EOF
            docker pull fazriridwan/ms-fazri-betest:latest
            docker stop ms-fazri-betest || true
            docker rm ms-fazri-betest || true
            docker run -d --name ms-fazri-betest -p 8080:8080 --env-file .env fazriridwan/ms-fazri-betest:latest
          EOF

        # run: |
        #   sudo apt-get update -qq && sudo apt-get install -y -qq sshpass
        #   script -qc "sshpass -p $HOST_SSH_PASSWORD ssh -p $HOST_SSH_PORT $HOST_SSH_USERNAME@$HOST_IP 'cd /home/ursklap/projects; git clone git@github.com:fazriridwan19/ms-fazri-betest.git'"
        #   script -qc "sshpass -p $HOST_SSH_PASSWORD ssh -p $HOST_SSH_PORT $HOST_SSH_USERNAME@$HOST_IP 'cd /home/ursklap/projects/ms-fazri-betest; make deploy-dev'"
